### ISSUE TITLE
wrong offset in the initrd image for s390x vm

### ISSUE THREAD

**Issue by jordimassaguerpla** [openSUSE/kiwi#440]
Hi Marcus,

when creating a s390x virtual machine, kiwi appends an offset to initrd image at the zipl configuration:

ramdisk = boot/initrd.vmx,0x4000000

However, running the resulting virtual image with kvm does not boot, but it does if we change this configuration with:

ramdisk = boot/initrd.vmx

and rerun zipl command (after the appropiate chroot).

Looking at the code, I see this is actually done in

https://github.com/openSUSE/kiwi/blob/master/modules/KIWIBoot.pm#L5136

What I don't know if this is a bug or a special case that should be considered. What's the 0x4000000 offfset for?

**Comment by schaefi** [comment]
I got this information from the s390 people a long time ago. I recently build images for s390 and they boot within the s390 zVM environment as well as on an LPAR. I can't tell if this is a problem of the s390 emulation in kvm or if I'm doing something wrong here

Thus I suggest you ask Ihno and/or Alex Graf for details on the load offset the initrd is loaded from
I'm fine removing the address if I got the ok from the s390 experts :)

**Comment by schaefi** [comment]
ok this one is not a kiwi but a kvm bug

The reason it breaks is that the boot loader code puts its virtio queue
at 100MB:

>     info.queue = (100ULL * 1024ULL* 1024ULL);

If we now have an initrd of reasonable size (and kiwi initrds are
*huge*) and put it at 64MB, we overlap with the virtio rings and corrupt
our virtio-blk communication.

Maybe we should change the
code so that it puts the virtio rings to top of memory - a few mb
instead. Or to be on the safe side at MIN(TOM - 2 * MB, 1<<31).

... handed over to kvm team
