### ISSUE TITLE
oem image with overlayfs - rw fs ext3 hardcoded

### ISSUE THREAD

**Issue by magist3r** [openSUSE/kiwi#565]
Hi!

It would be nice to choose fs for rw partition in case of overlayfs for oem image. For now ext3 is hardcoded in KIWIBoot.pm

**Comment by schaefi** [comment]
This has been addressed in #475 

```
       attribute hybridpersistent_filesystem {
            "btrfs" | "fat" | "exfat" | "ext4" | "xfs"
        }
```

**Comment by magist3r** [comment]
No it's not. This works for type="iso" flags="overlay", but not for type="oem" filesystem="overlayfs"

**Comment by schaefi** [comment]
yes you are right

**Comment by schaefi** [comment]
I do not recommend to make use of overlayfs for oem disk images. The reasons are

* dracut does not really support split root systems (you would need to write a module for it)
* cow performance is not sufficient for productive preload systems

just my 2cents

**Comment by magist3r** [comment]
The reason why I use overlayfs is small storage on target systems (1Gb internal flash). So I need squashfs compressed image to simply put all software on flash and save some space to user files. 

Big kiwi initrd is not a problem, because installer creates 200Mb boot partition.
The problem is that ext3 sometimes generating read/write errors in my case, and I want to try another fs (xfs for example) for read-write partition.

If there is another option besides overlayfs, please let me know.

**Comment by schaefi** [comment]
ok understood. Actually people investigated the same I/O errors and this was the reason why we introduced the hybridpersistent_filesystem attribute to let them use another fs for the read-write space.

As you already mentioned this attribute does not work if you build the image as oem. I guess the only reason why you build it as oem and not as hybrid iso is the installer capability is that correct ?

**Comment by schaefi** [comment]
The following might be interesting for you with regards to compressed root filesystems and OEM deployment in the new kiwi version (next generation) from here: https://github.com/SUSE/kiwi

* The support for split oem systems has been dropped due to stability and performance issues
  when used in productive environments which is the target system for oem deployments. The
  alternative here is to use a filesystem which natively supports compression. Therefore we
  recommend for compressed oem deployments to use

   ```xml
   <type image="oem" .... filesystem="btrfs"  fsmountoptions="compress=lzo"/>
   ```

* For Stick and/or live images the iso type should be used which also allows to select the read-write
  filesystem used together with the overlayfs. We do not recommend this type of image in an
  environment which requires data protection. Thus no deployment concept other than the manual
  dd on the storage device is provided

Hope this makes sense to you.

If you need additional functionality please report on https://github.com/SUSE/kiwi/issues

Thanks
