### ISSUE TITLE
repo imageinclude doesn't work for yum

### ISSUE THREAD

**Issue by k0da** [openSUSE/kiwi#592]
repository attribute allowing to keep repo in image doen't work for yum pkg manger

**Comment by schaefi** [comment]
This has been addressed in a clean way in the latest kiwi code base here:
https://github.com/SUSE/kiwi/blob/master/kiwi/system/setup.py#L112

you can workaround the issue here by providing the .repo files for yum as overlay files or archive
I'm afraid there won't be resources to fix non critical or L3 bugs in the v7 code base
