### ISSUE TITLE
kiwi platform support

### ISSUE THREAD

**Issue by doctording** [openSUSE/kiwi#649]
It seems that kiwi does not support arm64 platform.

**Comment by probonopd** [comment]
It certainly does. I am using it every day. It is called `x86_64`.

**Comment by doctording** [comment]
I'm sorry. I mean "aarch64" ($uname -a ) , not "x86_64".

**Comment by probonopd** [comment]
Sorry, I misread your first post, you are actually talking about ARM. I can say that I have used OBS with `aarch64` successfully to generate AppImages but I have not tried kiwi images so far.

**Comment by probonopd** [comment]
There are images for Raspberry Pi 3, don't know whether they are generated using kiwi:
https://en.opensuse.org/HCL:Raspberry_Pi3

**Comment by probonopd** [comment]
What would be cool btw is if we could use squashfs/unionfs (like a live ISO) for these devices. So that they become immune against plugging the power mid-operation. Should also sove some write cycles on the SD card.

**Comment by doctording** [comment]
thanks a lot. 
I use kiwi to make kiwi images: .iso,  .raw,  .qcow2(https://en.wikipedia.org/wiki/Qcow) etc.

**Comment by davidcassany** [comment]
@doctording, as @probonopd said kiwi can be used in ARM, recent KIWI versions can be found in openSUSE ports to ARM and other architectures. Also you should be capable to `pip install kiwi` in a ARM host, even I haven't tried it so far.

Please note that building ARM images is quite tricky since they are hardware dependent. The image will have to be aligned to a specific hardware, as it happens with Raspberry or other boards, see [here](https://build.opensuse.org/package/show/devel:ARM:Factory:Contrib:RaspberryPi3/JeOS-raspberrypi3.aarch64).
