### ISSUE TITLE
Missed RHEL_7 and CentOS_7 Appliances

### ISSUE THREAD

**Issue by sab-systems** [openSUSE/kiwi#650]
## Problem description
we are actually using Kiwi 7.04.8 for building Rhel6 and -7 and CentOS6 and -7 images.
Those builds acutally failed because it seems that the Appliances package repositorires had been removed from the opensuse build repo server:

http://download.opensuse.org/repositories/Virtualization:/Appliances/RHEL_7
http://download.opensuse.org/repositories/Virtualization:/Appliances/CentOS_7
http://download.opensuse.org/repositories/Virtualization:/Appliances/RedHat_RHEL-6
http://download.opensuse.org/repositories/Virtualization:/Appliances/CentOS_CentOS-6

Was the deletion on purpose or did they move to an other repository branch?

## Actual behaviour
kiwi logfile:

Aug-14 10:55:55 <1> : Creating yum metadata cache...
Aug-14 10:55:55 <1> : EXEC [/usr/bin/yum -c /var/cache/kiwi/yum/yum.conf -y makecache 2>&1]
Aug-14 10:55:56 <3> : yum: http://download.opensuse.org/repositories/Virtualization%3A/Appliances/RHEL_7/repodata/repomd.xml: [Errno 14] HTTP Error 404 : http://download.opensuse.org/repositories/Virtualization%3A/Appliances/RHEL_7/repodata/repomd.xml
Trying other mirror.
Error: Cannot retrieve repository metadata (repomd.xml) for repository: http:__download.opensuse.org_repositories_Virtualization:_Appliances_RHEL_7. Please verify its path and try again

## Steps to reproduce the behaviour
w3m -dump http://download.opensuse.org/repositories/Virtualization:/Appliances/RHEL_7
Resource is no longer available!

The requested URL is no longer available on this server and there is no
forwarding address. If you followed a link from a foreign page, please contact
the author of this page.

If you think this is a server error, please contact the webmaster.

Error 404

**Comment by davidcassany** [comment]
@sab-systems, sorry for late answer in this issue.

You are using an outdated kiwi version in order to build CentOS and RHEL images. Kiwi v7 is currently in maintenance mode and all efforts on improving and enhancing KIWI with new features take place in the [KIWI-NG](http://github.com/SUSE/kiwi), a complete rewrite with modern technologies.

Also the repositories for other distributions have been removed, since KIWI-NG can be installed via `pip` also in other distributions. With `pip search kiwi` you should be capable to see the new and latest version of KIWI.

I recommend to switch to the new version since it has better support for CentOS and RHEL. You can see some examples of kiwi description files for several distributions (including CentOS and RHEL) in this [repository](https://github.com/SUSE/kiwi-descriptions).
